# Generated by Django 2.2.16 on 2023-03-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тип кузова не выбран', max_length=50)),
            ],
            options={
                'verbose_name': 'Кузов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Марка',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='Модель не выбрана', max_length=100)),
                ('complect', models.CharField(blank=True, max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(default=2023)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('body', models.ForeignKey(blank=True, help_text='Кузов автомобиля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.Body', verbose_name='Кузов')),
                ('mark', models.ForeignKey(blank=True, help_text='Кузов автомобиля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.Mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'ordering': ('mark',),
            },
        ),
    ]
