# Generated by Django 2.2.16 on 2023-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'ordering': ('name',), 'verbose_name': 'Кузов', 'verbose_name_plural': 'Кузова'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('mark',), 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ('name',), 'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterField(
            model_name='body',
            name='name',
            field=models.CharField(default='Тип кузова не выбран', max_length=50, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='complect',
            field=models.CharField(blank=True, max_length=70, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='Модель не выбрана', max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Марка'),
        ),
    ]
